name: Generate Infrastructure Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          python -m pip install --upgrade pip
          pip install diagrams python-hcl2

      - name: Crear archivo Python temporal con el cÃ³digo
        run: |
          echo "
          import os
          import hcl2
          from diagrams import Diagram, Cluster, Node
          from diagrams.aws.compute import EC2
          from diagrams.aws.database import RDS
          from diagrams.aws.network import VPC
          
          # Crear un diagrama
          with Diagram('AWS Infrastructure', show=False, filename='diagram'):
              vpc = VPC('VPC')
              with Cluster('App Layer'):
                  ec2_instance = EC2('EC2 Instance')
              with Cluster('Database Layer'):
                  rds_instance = RDS('RDS Instance')

              vpc >> ec2_instance >> rds_instance
          " > script.py

      - name: Generar el diagrama
        run: |
          python script.py

      - name: Commit and Push Diagram
        run: |
          git config --local user.name "JesusHuallpa"
          git config --local user.email "jh2021071085@virtual.upt.pe"
          git add diagram.png
          git commit -m "Add AWS infrastructure diagram"
          git push

      - name: Subir el diagrama generado como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: infrastructure-diagram
          path: diagram.png
